### PR TITLE
[rc] test with clang 17

### PR DESCRIPTION
**Pull request by h-vetinari**
The move to clang 17 in conda-forge will happen as soon as we fix some last outstanding issues, and given that clang 17 seemed to fail in #251, open this PR to figure out what's up.

### CODE REVIEW

**Comment by h-vetinari** [comment]
Though I have absolutely zero idea how this interacts with the compilation errors we [had seen](https://github.com/conda-forge/arcticdb-feedstock/pull/251#issuecomment-2254513581), the problems seem to have gone away with the non-hardened libcxx builds...? 🤔 

Still a head-scratcher, but good news at least 😅

**Comment by jjerphan** [comment]
I would not be surprised if UBs exist in folly since it's quite a complex project.

**Comment by h-vetinari** [comment]
> I would not be surprised if UBs exist in folly since it's quite a complex project.

Yeah, but we didn't get a segfault during compilation, but a proper compilation error. Well, I guess that's one of the benefits of the hardened libcxx (except that now you have to fix all your dependencies to enable testing with it 🤣)

**Comment by jjerphan** [comment]
:smiling_face_with_tear:

**Comment by h-vetinari** [comment]
Closing this PR as it has served its purpose
